name: BestCF

on:
  push:
    branches:
      - main

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@vv4.2.0

    - name: Set up Python
      uses: actions/setup-python@vv4.2.0
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: BestCF
      run: |
        python .github/workflows/bestcf.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
