name: Update proxy IP

on:
  push:
    branches:
      - main
    paths:
      - 'update_ip.py'
      - 'blank.yml'

  schedule:
    - cron: '*/10 * * * *'

jobs:
  update_ip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy IP
      env:
        ME_GITHUB_TOKEN: ${{ secrets.ME_GITHUB_TOKEN }}
        DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}
      run: python .github/workflows/update_ip.py
