name: ONECF

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: ONECF
      run: |
        python .github/workflows/onecf.py
      env:
        DNSAPI: ${{ secrets.DNSAPI }}
        DOMAINS: ${{ secrets.DOMAINS }}
        ONECF_CLOUDFLARE_API_TOKEN: ${{ secrets.ONECF_CLOUDFLARE_API_TOKEN }}
        ONECF_CLOUDFLARE_ZONE_ID: ${{ secrets.ONECF_CLOUDFLARE_ZONE_ID }}
