name: Dns-xyz

on:
  push:
    branches:
      - main
    paths:
      - 'best-ip.txt'


jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # 使用你想要的 Python 版本

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python .github/workflows/xyz.py
      env:
        xyzCLOUDFLARE_API_TOKEN: ${{ secrets.xyzCLOUDFLARE_API_TOKEN }}
        xyzZONE_ID: ${{ secrets.xyzZONE_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        API_URL: ${{ secrets.API_URL }}
